package hy.tmc.cli.testhelpers;

public class ExampleJSON {

    public static String courseExample = "{\n"
            + "\n"
            + "    \"api_version\": 7,\n"
            + "    \"course\": \n"
            + "\n"
            + "{\n"
            + "\n"
            + "    \"id\": 4,\n"
            + "    \"name\": \"mooc-part2-english\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/4.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/4/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/4/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "[\n"
            + "\n"
            + "    \"http://staging.spyware.testmycode.net/\"\n"
            + "\n"
            + "],\n"
            + "\"unlockables\": [ ],\n"
            + "\"exercises\": \n"
            + "[\n"
            + "\n"
            + "{\n"
            + "\n"
            + "    \"id\": 642,\n"
            + "    \"name\": \"week7-week7_01.Smileys\",\n"
            + "    \"locked\": false,\n"
            + "    \"deadline_description\": null,\n"
            + "    \"deadline\": null,\n"
            + "    \"checksum\": \"5faf0a5654d2a92e7701d76a94c36148\",\n"
            + "    \"return_url\": \"https://tmc.mooc.fi/staging/exercises/642/submissions.json\",\n"
            + "    \"zip_url\": \"https://tmc.mooc.fi/staging/exercises/642.zip\",\n"
            + "    \"returnable\": true,\n"
            + "    \"requires_review\": false,\n"
            + "    \"attempted\": false,\n"
            + "    \"completed\": false,\n"
            + "    \"reviewed\": false,\n"
            + "    \"all_review_points_given\": true,\n"
            + "    \"memory_limit\": null,\n"
            + "    \"runtime_params\": [ ],\n"
            + "    \"valgrind_strategy\": null,\n"
            + "    \"code_review_requests_enabled\": true,\n"
            + "    \"run_tests_locally_action_enabled\": true,\n"
            + "    \"exercise_submissions_url\": \"https://tmc.mooc.fi/staging/exercises/642.json?api_version=7\"\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 643,\n"
            + "    \"name\": \"week7-week7_02.CharacterStringChanger\",\n"
            + "    \"locked\": false,\n"
            + "    \"deadline_description\": null,\n"
            + "    \"deadline\": null,\n"
            + "    \"checksum\": \"cd26e60472c58d55938ee0defce6caaa\",\n"
            + "    \"return_url\": \"https://tmc.mooc.fi/staging/exercises/643/submissions.json\",\n"
            + "    \"zip_url\": \"https://tmc.mooc.fi/staging/exercises/643.zip\",\n"
            + "    \"returnable\": true,\n"
            + "    \"requires_review\": false,\n"
            + "    \"attempted\": false,\n"
            + "    \"completed\": false,\n"
            + "    \"reviewed\": false,\n"
            + "    \"all_review_points_given\": true,\n"
            + "    \"memory_limit\": null,\n"
            + "    \"runtime_params\": [ ],\n"
            + "    \"valgrind_strategy\": null,\n"
            + "    \"code_review_requests_enabled\": true,\n"
            + "    \"run_tests_locally_action_enabled\": true,\n"
            + "    \"exercise_submissions_url\": \"https://tmc.mooc.fi/staging/exercises/643.json?api_version=7\"\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 644,\n"
            + "    \"name\": \"week7-week7_03.Calculator\",\n"
            + "    \"locked\": false,\n"
            + "    \"deadline_description\": null,\n"
            + "    \"deadline\": null,\n"
            + "    \"checksum\": \"01fea281b9bb0f7b62442711129d6efe\",\n"
            + "    \"return_url\": \"https://tmc.mooc.fi/staging/exercises/644/submissions.json\",\n"
            + "    \"zip_url\": \"https://tmc.mooc.fi/staging/exercises/644.zip\",\n"
            + "    \"returnable\": true,\n"
            + "    \"requires_review\": false,\n"
            + "    \"attempted\": false,\n"
            + "    \"completed\": false,\n"
            + "    \"reviewed\": false,\n"
            + "    \"all_review_points_given\": true,\n"
            + "    \"memory_limit\": null,\n"
            + "    \"runtime_params\": [ ],\n"
            + "    \"valgrind_strategy\": null,\n"
            + "    \"code_review_requests_enabled\": true,\n"
            + "    \"run_tests_locally_action_enabled\": true,\n"
            + "    \"exercise_submissions_url\": \"https://tmc.mooc.fi/staging/exercises/644.json?api_version=7\"\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 645,\n"
            + "    \"name\": \"week7-week7_04.ThingSuitcaseAndContainer\",\n"
            + "    \"locked\": false,\n"
            + "    \"deadline_description\": null,\n"
            + "    \"deadline\": null,\n"
            + "    \"checksum\": \"f624492ad33751936205a45ae967754c\",\n"
            + "    \"return_url\": \"https://tmc.mooc.fi/staging/exercises/645/submissions.json\",\n"
            + "    \"zip_url\": \"https://tmc.mooc.fi/staging/exercises/645.zip\",\n"
            + "    \"returnable\": true,\n"
            + "    \"requires_review\": false,\n"
            + "    \"attempted\": false,\n"
            + "    \"completed\": false,\n"
            + "    \"reviewed\": false,\n"
            + "    \"all_review_points_given\": true,\n"
            + "    \"memory_limit\": null,\n"
            + "    \"runtime_params\": [ ],\n"
            + "    \"valgrind_strategy\": null,\n"
            + "    \"code_review_requests_enabled\": true,\n"
            + "    \"run_tests_locally_action_enabled\": true,\n"
            + "    \"exercise_submissions_url\": \"https://tmc.mooc.fi/staging/exercises/645.json?api_version=7\"\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 646,\n"
            + "    \"name\": \"week7-week7_05.Nicknames\",\n"
            + "    \"locked\": false,\n"
            + "    \"deadline_description\": null,\n"
            + "    \"deadline\": null,\n"
            + "    \"checksum\": \"40df65f029797aacc02fddb64fc68048\",\n"
            + "    \"return_url\": \"https://tmc.mooc.fi/staging/exercises/646/submissions.json\",\n"
            + "    \"zip_url\": \"https://tmc.mooc.fi/staging/exercises/646.zip\",\n"
            + "    \"returnable\": true,\n"
            + "    \"requires_review\": false,\n"
            + "    \"attempted\": false,\n"
            + "    \"completed\": false,\n"
            + "    \"reviewed\": false,\n"
            + "    \"all_review_points_given\": true,\n"
            + "    \"memory_limit\": null,\n"
            + "    \"runtime_params\": [ ],\n"
            + "    \"valgrind_strategy\": null,\n"
            + "    \"code_review_requests_enabled\": true,\n"
            + "    \"run_tests_locally_action_enabled\": true,\n"
            + "    \"exercise_submissions_url\": \"https://tmc.mooc.fi/staging/exercises/646.json?api_version=7\"\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 647,\n"
            + "    \"name\": \"week7-week7_06.PromissoryNote\",\n"
            + "    \"locked\": false,\n"
            + "    \"deadline_description\": null,\n"
            + "    \"deadline\": null,\n"
            + "    \"checksum\": \"726505ae5025291490cf1fa6a251e53c\",\n"
            + "    \"return_url\": \"https://tmc.mooc.fi/staging/exercises/647/submissions.json\",\n"
            + "    \"zip_url\": \"https://tmc.mooc.fi/staging/exercises/647.zip\",\n"
            + "    \"returnable\": true,\n"
            + "    \"requires_review\": false,\n"
            + "    \"attempted\": false,\n"
            + "    \"completed\": false,\n"
            + "    \"reviewed\": false,\n"
            + "    \"all_review_points_given\": true,\n"
            + "    \"memory_limit\": null,\n"
            + "    \"runtime_params\": [ ],\n"
            + "    \"valgrind_strategy\": null,\n"
            + "    \"code_review_requests_enabled\": true,\n"
            + "    \"run_tests_locally_action_enabled\": true,\n"
            + "    \"exercise_submissions_url\": \"https://tmc.mooc.fi/staging/exercises/647.json?api_version=7\"\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 648,\n"
            + "    \"name\": \"week7-week7_07.Dictionary\",\n"
            + "    \"locked\": false,\n"
            + "    \"deadline_description\": null,\n"
            + "    \"deadline\": null,\n"
            + "    \"checksum\": \"434aaa0bca6d0d510d456b4c5e5c8a37\",\n"
            + "    \"return_url\": \"https://tmc.mooc.fi/staging/exercises/648/submissions.json\",\n"
            + "    \"zip_url\": \"https://tmc.mooc.fi/staging/exercises/648.zip\",\n"
            + "    \"returnable\": true,\n"
            + "    \"requires_review\": false,\n"
            + "    \"attempted\": false,\n"
            + "    \"completed\": false,\n"
            + "    \"reviewed\": false,\n"
            + "    \"all_review_points_given\": true,\n"
            + "    \"memory_limit\": null,\n"
            + "    \"runtime_params\": [ ],\n"
            + "    \"valgrind_strategy\": null,\n"
            + "    \"code_review_requests_enabled\": true,\n"
            + "    \"run_tests_locally_action_enabled\": true,\n"
            + "    \"exercise_submissions_url\": \"https://tmc.mooc.fi/staging/exercises/648.json?api_version=7\"\n"
            + "\n"
            + "},\n"
            + "\n"
            + "            {\n"
            + "                \"id\": 649,\n"
            + "                \"name\": \"week7-week7_08.Airport\",\n"
            + "                \"locked\": false,\n"
            + "                \"deadline_description\": null,\n"
            + "                \"deadline\": null,\n"
            + "                \"checksum\": \"fafe732367388d42a252a26cb5e81f06\",\n"
            + "                \"return_url\": \"https://tmc.mooc.fi/staging/exercises/649/submissions.json\",\n"
            + "                \"zip_url\": \"https://tmc.mooc.fi/staging/exercises/649.zip\",\n"
            + "                \"returnable\": true,\n"
            + "                \"requires_review\": false,\n"
            + "                \"attempted\": false,\n"
            + "                \"completed\": false,\n"
            + "                \"reviewed\": false,\n"
            + "                \"all_review_points_given\": true,\n"
            + "                \"memory_limit\": null,\n"
            + "                \"runtime_params\": [ ],\n"
            + "                \"valgrind_strategy\": null,\n"
            + "                \"code_review_requests_enabled\": true,\n"
            + "                \"run_tests_locally_action_enabled\": true,\n"
            + "                \"exercise_submissions_url\": \"https://tmc.mooc.fi/staging/exercises/649.json?api_version=7\"\n"
            + "            }\n"
            + "        ]\n"
            + "    }\n"
            + "\n"
            + "}";
    public static String coursesExample = "{\n"
            + "\n"
            + "    \"api_version\": 7,\n"
            + "    \"courses\": \n"
            + "\n"
            + "[\n"
            + "\n"
            + "{\n"
            + "\n"
            + "    \"id\": 3,\n"
            + "    \"name\": \"2013_ohpeJaOhja\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/3.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/3/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/3/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 13,\n"
            + "    \"name\": \"2013-OOProgrammingWithJava-PART1\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/13.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/13/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/13/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 19,\n"
            + "    \"name\": \"2014-mooc-no-deadline\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/19.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/19/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/19/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 7,\n"
            + "    \"name\": \"c-demo\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/7.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/7/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/7/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 14,\n"
            + "    \"name\": \"checkstyle-demo\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/14.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/14/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/14/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 1,\n"
            + "    \"name\": \"demo\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/1.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/1/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/1/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 28,\n"
            + "    \"name\": \"disable-local-tests\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/28.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/28/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/28/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 9,\n"
            + "    \"name\": \"eclipseAntTest\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/9.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/9/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/9/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 10,\n"
            + "    \"name\": \"jamo_demo\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/10.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/10/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/10/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 8,\n"
            + "    \"name\": \"k14-ohpe\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/8.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/8/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/8/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 29,\n"
            + "    \"name\": \"k2015-ohpe\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/29.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/29/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/29/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 21,\n"
            + "    \"name\": \"k2015-tira\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/21.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/21/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/21/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 4,\n"
            + "    \"name\": \"mooc-part2-english\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/4.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/4/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/4/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 22,\n"
            + "    \"name\": \"rails4-test\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/22.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/22/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/22/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 23,\n"
            + "    \"name\": \"rails4-test2\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/23.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/23/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/23/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 25,\n"
            + "    \"name\": \"review_request\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/25.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/25/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/25/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 15,\n"
            + "    \"name\": \"s2014-tira\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/15.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/15/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/15/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 12,\n"
            + "    \"name\": \"tmc-eclipse\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/12.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/12/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/12/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 27,\n"
            + "    \"name\": \"tmc-testcourse\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/27.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/27/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/27/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 18,\n"
            + "    \"name\": \"WEPAMOOC-STAGE\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/18.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/18/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/18/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 5,\n"
            + "    \"name\": \"WEPATEST\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/5.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/5/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/5/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 26,\n"
            + "    \"name\": \"weso-stage\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/26.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/26/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/26/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "    [\n"
            + "        \"http://staging.spyware.testmycode.net/\"\n"
            + "    ]\n"
            + "\n"
            + "},\n"
            + "{\n"
            + "\n"
            + "    \"id\": 24,\n"
            + "    \"name\": \"weso-test\",\n"
            + "    \"details_url\": \"https://tmc.mooc.fi/staging/courses/24.json\",\n"
            + "    \"unlock_url\": \"https://tmc.mooc.fi/staging/courses/24/unlock.json\",\n"
            + "    \"reviews_url\": \"https://tmc.mooc.fi/staging/courses/24/reviews.json\",\n"
            + "    \"comet_url\": \"https://tmc.mooc.fi:8443/comet\",\n"
            + "    \"spyware_urls\": \n"
            + "\n"
            + "            [\n"
            + "                \"http://staging.spyware.testmycode.net/\"\n"
            + "            ]\n"
            + "        }\n"
            + "    ]\n"
            + "\n"
            + "}";
}
